-- V7 Migration 0003: share expire/revoke fields (if missing)

ALTER TABLE shares
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS watermark BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS download_allowed BOOLEAN NOT NULL DEFAULT FALSE;
