// AUTO-GENERATED. DO NOT EDIT.
// source: /var/www/stellcodex/frontend/src/security/access-control.source.json

export const PERMISSION_KEYS = [
  "admin.comments.disable_on_file",
  "admin.comments.enable_on_file",
  "admin.files.archive",
  "admin.files.delete",
  "admin.files.hide",
  "admin.files.purge_versions",
  "admin.files.read",
  "admin.files.storage_purge",
  "admin.files.unarchive",
  "admin.files.unhide",
  "admin.files.view_metadata",
  "admin.files.view_processing_history",
  "admin.library.assign_category",
  "admin.library.curate_basic",
  "admin.library.feature",
  "admin.library.read",
  "admin.library.remove_from_library",
  "admin.library.unfeature",
  "admin.notes.read",
  "admin.notes.remove",
  "admin.presentations.delete",
  "admin.presentations.lock",
  "admin.presentations.read",
  "admin.presentations.unlock",
  "admin.shares.downgrade_permission",
  "admin.shares.make_public",
  "admin.shares.org_wide",
  "admin.shares.read",
  "admin.shares.remove_expiry",
  "admin.shares.revoke",
  "admin.shares.set_expiry",
  "admin.shares.set_no_expiry",
  "admin.shares.upgrade_permission",
  "admin.users.delete",
  "admin.users.disable_sharing",
  "admin.users.enable_sharing",
  "admin.users.read",
  "admin.users.revoke_sessions",
  "admin.users.suspend",
  "admin.users.unsuspend",
  "ai.suggestions.approve",
  "ai.suggestions.read",
  "ai.suggestions.reject",
  "analytics.read_aggregate",
  "approvals.approve",
  "approvals.cancel",
  "approvals.execute",
  "approvals.read",
  "approvals.reject",
  "approvals.request_create",
  "logs.audit.read",
  "logs.export_full",
  "logs.export_redacted",
  "logs.system.read_full",
  "logs.system.read_redacted",
  "rbac.assignments.read",
  "rbac.assignments.update",
  "rbac.roles.create",
  "rbac.roles.delete",
  "rbac.roles.read",
  "rbac.roles.update",
  "security.abuse.read",
  "security.emergency.disable_public_shares",
  "security.emergency.disable_uploads",
  "security.emergency.enable_public_shares",
  "security.emergency.enable_uploads",
  "security.emergency.readonly_disable",
  "security.emergency.readonly_enable",
  "security.files.quarantine",
  "security.files.unquarantine",
  "security.ip.block",
  "security.ip.unblock",
  "security.policies.read",
  "security.policies.update",
  "system.backups.read",
  "system.backups.restore_test",
  "system.deploy.read",
  "system.deploy.rollback",
  "system.queues.pause",
  "system.queues.read",
  "system.queues.resume",
  "system.queues.set_concurrency",
  "system.secrets.rotate",
  "system.status.read",
  "system.workers.restart",
  "system.workers.scale"
] as const;

export type PermissionKey = typeof PERMISSION_KEYS[number];

export function isPermissionKey(value: string): value is PermissionKey {
  return (PERMISSION_KEYS as readonly string[]).includes(value);
}
