model_list:
  - model_name: local_fast
    litellm_params:
      model: ollama/qwen2.5:0.5b
      api_base: http://orchestra_ollama:11434
      api_key: none

  - model_name: local_reason
    litellm_params:
      model: ollama/qwen2.5:0.5b
      api_base: http://orchestra_ollama:11434
      api_key: none

litellm_settings:
  drop_params: true
