#!/usr/bin/env python3
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


WORKSPACE = Path("/root/workspace")
RUNS_DIR = WORKSPACE / "_runs" / "pipeline_doctor"
PROJECT_ROOT = Path("/var/www/stellcodex")

DEMO_RELATIVE_PATH = "docs/archive/pipeline-repair-runner-demo.md"
DEMO_MARKER = "PIPELINE_REPAIR_DEMO_OK"


def utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def compact_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def run_text_command(cmd):
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
    return proc.returncode, proc.stdout.strip(), proc.stderr.strip()


def git_context():
    branch = run_text_command(["git", "-C", str(PROJECT_ROOT), "rev-parse", "--abbrev-ref", "HEAD"])[1]
    head = run_text_command(["git", "-C", str(PROJECT_ROOT), "rev-parse", "--short", "HEAD"])[1]
    return {"branch": branch, "head": head}


def demo_file_content() -> str:
    return (
        "# Pipeline Repair Runner Demo\n\n"
        "- status: generated by isolated repair runner demo\n"
        "- marker: %s\n"
        "- scope: safe docs-only diff\n" % DEMO_MARKER
    )


def main() -> int:
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    stamp = compact_stamp()
    bundle_dir = RUNS_DIR / ("%s_demo_repair_bundle" % stamp)
    bundle_dir.mkdir(parents=True, exist_ok=True)

    git = git_context()
    report = {
        "generated_at": utc_iso(),
        "status": "FAIL",
        "base_url": "demo://pipeline-repair-runner",
        "sample_file": "",
        "steps": [
            {
                "name": "demo_marker_check",
                "command": [
                    "bash",
                    "-lc",
                    "test -f %s && grep -q %s %s"
                    % (DEMO_RELATIVE_PATH, DEMO_MARKER, DEMO_RELATIVE_PATH),
                ],
                "status": "FAIL",
                "exit_code": 1,
                "duration_seconds": 0.0,
                "started_at": utc_iso(),
                "stdout": "",
                "stderr": "Demo marker file missing.",
                "root_cause_hint": "Demo marker file is missing; create the docs-only demo file with the expected marker.",
            }
        ],
        "summary": "demo_marker_check failed: Demo marker file is missing; create the docs-only demo file with the expected marker.",
        "report_path": str(bundle_dir / "report.json"),
    }
    (bundle_dir / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    pr_metadata = {
        "suggested_branch": "doctor/%s-demo-repair-runner" % stamp,
        "commit_message": "chore: add pipeline repair runner demo marker",
        "pr_title": "chore: add pipeline repair runner demo marker",
        "pr_body": (
            "## Summary\n"
            "- Add the docs-only demo marker file used to validate the isolated repair runner.\n\n"
            "## Safety\n"
            "- Only modifies %s\n"
        )
        % DEMO_RELATIVE_PATH,
        "candidate_files": [DEMO_RELATIVE_PATH],
    }
    (bundle_dir / "pr_metadata.json").write_text(
        json.dumps(pr_metadata, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    prompt = (
        "# Pipeline Repair Runner Demo Prompt\n\n"
        "You are in an isolated git worktree.\n"
        "Create exactly one new file at `%s` with the exact content below.\n"
        "Do not modify any other file.\n"
        "After writing the file, stop.\n\n"
        "```md\n%s```\n"
    ) % (DEMO_RELATIVE_PATH, demo_file_content())
    (bundle_dir / "repair_prompt.md").write_text(prompt, encoding="utf-8")

    git_payload = {
        "branch": git["branch"],
        "head": git["head"],
        "status": "## %s...%s" % (git["branch"], "origin/%s" % git["branch"]),
        "errors": [],
    }
    (bundle_dir / "git_context.json").write_text(
        json.dumps(git_payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    readme = (
        "# Pipeline Demo Repair Bundle\n\n"
        "This bundle exists to prove that the repair runner can create a safe docs-only diff in an isolated worktree.\n\n"
        "Target file: `%s`\n"
        "Marker: `%s`\n"
    ) % (DEMO_RELATIVE_PATH, DEMO_MARKER)
    (bundle_dir / "README.md").write_text(readme, encoding="utf-8")

    print("Demo repair bundle: %s" % bundle_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
