# AUTO-GENERATED. DO NOT EDIT.
ACCESS_CONTROL = {
  "roles": [
    "owner",
    "admin",
    "support",
    "moderator",
    "user"
  ],
  "permissions": [
    "admin.users.read",
    "admin.users.suspend",
    "admin.users.unsuspend",
    "admin.users.revoke_sessions",
    "admin.users.disable_sharing",
    "admin.users.enable_sharing",
    "admin.users.delete",
    "admin.files.read",
    "admin.files.hide",
    "admin.files.unhide",
    "admin.files.archive",
    "admin.files.unarchive",
    "admin.files.delete",
    "admin.files.view_metadata",
    "admin.files.view_processing_history",
    "admin.files.purge_versions",
    "admin.files.storage_purge",
    "admin.shares.read",
    "admin.shares.revoke",
    "admin.shares.set_expiry",
    "admin.shares.remove_expiry",
    "admin.shares.downgrade_permission",
    "admin.shares.upgrade_permission",
    "admin.shares.make_public",
    "admin.shares.set_no_expiry",
    "admin.shares.org_wide",
    "admin.presentations.read",
    "admin.presentations.lock",
    "admin.presentations.unlock",
    "admin.presentations.delete",
    "admin.notes.read",
    "admin.notes.remove",
    "admin.comments.disable_on_file",
    "admin.comments.enable_on_file",
    "admin.library.read",
    "admin.library.curate_basic",
    "admin.library.feature",
    "admin.library.unfeature",
    "admin.library.remove_from_library",
    "admin.library.assign_category",
    "system.status.read",
    "system.queues.read",
    "system.queues.pause",
    "system.queues.resume",
    "system.queues.set_concurrency",
    "system.workers.restart",
    "system.workers.scale",
    "system.deploy.read",
    "system.deploy.rollback",
    "system.backups.read",
    "system.backups.restore_test",
    "system.secrets.rotate",
    "security.policies.read",
    "security.policies.update",
    "security.abuse.read",
    "security.ip.block",
    "security.ip.unblock",
    "security.files.quarantine",
    "security.files.unquarantine",
    "security.emergency.readonly_enable",
    "security.emergency.readonly_disable",
    "security.emergency.disable_uploads",
    "security.emergency.enable_uploads",
    "security.emergency.disable_public_shares",
    "security.emergency.enable_public_shares",
    "logs.audit.read",
    "logs.system.read_redacted",
    "logs.system.read_full",
    "logs.export_redacted",
    "logs.export_full",
    "ai.suggestions.read",
    "ai.suggestions.approve",
    "ai.suggestions.reject",
    "analytics.read_aggregate",
    "rbac.roles.read",
    "rbac.roles.create",
    "rbac.roles.update",
    "rbac.roles.delete",
    "rbac.assignments.read",
    "rbac.assignments.update",
    "approvals.request_create",
    "approvals.read",
    "approvals.approve",
    "approvals.reject",
    "approvals.execute",
    "approvals.cancel"
  ],
  "role_grants": {
    "owner": [
      "*"
    ],
    "admin": [
      "*"
    ],
    "support": [
      "system.status.read"
    ],
    "moderator": [
      "system.status.read"
    ],
    "user": [
      "system.status.read"
    ]
  },
  "route_permissions": {
    "/dashboard": "system.status.read",
    "/dashboard/files": "system.status.read",
    "/dashboard/activity": "system.status.read",
    "/dashboard/settings": "system.status.read",
    "/admin": "system.status.read",
    "/admin/users": "admin.users.read",
    "/admin/files": "admin.files.read",
    "/admin/approvals": "approvals.read",
    "/admin/ai": "ai.suggestions.read",
    "/admin/audit": "logs.audit.read",
    "/admin/rbac": "rbac.roles.read",
    "/admin/system": "system.status.read"
  }
}
